"
"  ██╗   ██╗██╗███╗   ███╗██████╗  ██████╗
"  ██║   ██║██║████╗ ████║██╔══██╗██╔════╝
"  ██║   ██║██║██╔████╔██║██████╔╝██║     
"  ╚██╗ ██╔╝██║██║╚██╔╝██║██╔══██╗██║     
"   ╚████╔╝ ██║██║ ╚═╝ ██║██║  ██║╚██████╗
"    ╚═══╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝

so ~/.dotfiles/vim/plugins.vim      "Install and setup plugins 

" General
set number                          " Show line numbers
set nowrap                          " Wrap lines
set showmatch                       " Highlight matching brace
set textwidth=80                    " Line wrap (number of cols)
set laststatus=2                    " always show statusline
set showtabline=2
set mouse=a                         " allow mouse to move cursor
set clipboard=unnamed               " Lets vim and clipboard play nice togehter
set backspace=indent,eol,start      " Make backspace act normal
set splitbelow splitright           " Splits open below and to the right
set list listchars=tab:›\ ,trail:·  " Define how we show tabs and trailing spaces

" Indentation
set autoindent	                    " Auto-indent new lines
set expandtab                       " Use spaces instead of tabs
set shiftwidth=2                    " Number of auto-indent spaces
set smartindent                     " Enable smart-indent
set smarttab                        " Enable smart-tabs
set softtabstop=2                   " Number of spaces per Tab

" Search 
set hlsearch                        " Highlight all search results
set smartcase                       " Enable smart-case search
set ignorecase                      " Always case-insensitive
set incsearch                       " Searches for strings incrementally

" Colorscheme
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors
syntax enable
colorscheme gruvbox

let g:lightline = {
      \ 'colorscheme': 'gruvbox',
      \ }

" Remove hightlight color of whitespace
highlight SpecialKey ctermbg=NONE guibg=NONE

" Keybindings
map fd <Esc>
inoremap fd <Esc>

" Set scroll to be 3 times faster
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
