set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin "janoamaral/tokyo-night-tmux"

# Configure tmux-floax
set -g @floax-bind 'e'

# Configure tokyo-night plugin
set -g @tokyo-night-tmux_theme night    # storm | day | default to 'night'
set -g @tokyo-night-tmux_transparent 1  # 1 or 0
set -g @tokyo-night-tmux_window_id_style dsquare
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_date_format MDY
set -g @tokyo-night-tmux_time_format 12H
set -g @tokyo-night-tmux_show_path 0
set -g @tokyo-night-tmux_path_format relative # 'relative' or 'full'

# Configure the catppuccin plugin
# set -g @catppuccin_flavor "mocha"
# set -g @catppuccin_window_status_style "rounded"
# set -g @catppuccin_window_text " #W"
# set -g @catppuccin_window_current_text " #W"

# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# set -g status-left ""
# set -g status-right "#{E:@catppuccin_status_application}"
# set -agF status-right "#{E:@catppuccin_status_session}"


