# 
# ███████╗███████╗██╗  ██╗
# ╚══███╔╝██╔════╝██║  ██║
#   ███╔╝ ███████╗███████║
#  ███╔╝  ╚════██║██╔══██║
# ███████╗███████║██║  ██║
# ╚══════╝╚══════╝╚═╝  ╚═╝
#

source ~/.dotfiles/zsh/variables.zsh
source ~/.dotfiles/zsh/plugins.zsh
source ~/.dotfiles/zsh/completion.zsh
source ~/.dotfiles/zsh/aliases.zsh
source ~/.dotfiles/zsh/path.sh
source ~/.dotfiles/zsh/history.zsh
source ~/.dotfiles/zsh/keybindings.zsh
source ~/.dotfiles/zsh/functions.zsh

# echo "Welcome Back, Christian Valdez"
eval "$(mise activate zsh)"
eval "$(zoxide init --cmd cd zsh)"
